SELECT 
    A.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY, 
    SUM(B.PRICE * BS.SALES) AS TOTAL_SALES 
FROM BOOK B
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE MONTH(BS.SALES_DATE) = 1 AND YEAR(BS.SALES_DATE) = 2022
GROUP BY 1, 2, 3
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;