WITH A AS (
    SELECT C.CAR_ID, C.CAR_TYPE,
        FLOOR(C.DAILY_FEE * 0.3 * (100 - P.DISCOUNT_RATE))  AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
        ON C.CAR_TYPE = P.CAR_TYPE
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
        AND P.DURATION_TYPE = '30일 이상'
        AND C.CAR_ID NOT IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE <= '2022-11-30'
                AND END_DATE >= '2022-11-01'
        )
)
SELECT A.CAR_ID, A.CAR_TYPE, A.FEE 
FROM A
WHERE A.FEE >= 500000 AND A.FEE < 2000000
ORDER BY A.FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;

