WITH U AS (
    SELECT *
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
C AS (
    SELECT COUNT(*) AS CNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
SELECT
    YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT O.USER_ID) / C.CNT, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE O
JOIN U ON U.USER_ID = O.USER_ID
CROSS JOIN C
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC;