SELECT
    T.USER_ID,
    I.NICKNAME,
    T.TOTAL_SALES
FROM USED_GOODS_USER AS I
INNER JOIN (
    SELECT
        UGD.WRITER_ID AS USER_ID,
        SUM(UGD.PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD AS UGD
    WHERE UGD.STATUS = 'DONE'
    GROUP BY UGD.WRITER_ID
    HAVING SUM(UGD.PRICE) >= 700000
) AS T
ON T.USER_ID = I.USER_ID
ORDER BY T.TOTAL_SALES ASC;