WITH A AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT 
    MONTH(C.START_DATE) AS MONTH,
    C.CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
JOIN A
  ON A.CAR_ID = C.CAR_ID
WHERE C.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(C.START_DATE), C.CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;