SELECT FI.ID, FN.FISH_NAME, FI.LENGTH FROM FISH_INFO FI 
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO
    GROUP BY 1
) TMP 
    ON FI.FISH_TYPE = TMP.FISH_TYPE
    AND FI.LENGTH = TMP.LENGTH
JOIN FISH_NAME_INFO FN 
    ON TMP.FISH_TYPE = FN.FISH_TYPE
ORDER BY ID ASC;
