WITH A AS (
    SELECT T.CATEGORY, MAX(T.PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT T
    WHERE T.CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY T.CATEGORY
)
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN A
    ON A.CATEGORY = F.CATEGORY
    AND A.MAX_PRICE = F.PRICE
ORDER BY F.PRICE DESC;